# Configuraçãoes da Automação Impressão de Minuta GOL

# Pastas de entrada separadas por vírgula
pastas.entrada=C:/projetos/seaway-minuta-despacho/massa-de-testes/entrada/FAT/CSV,C:/projetos/seaway-minuta-despacho/massa-de-testes/entrada/LOJA/MINUTA

# Pastas de destino e temporária
pasta.processados=C:/projetos/seaway-minuta-despacho/massa-de-testes/processados
pasta.temp=C:/projetos/seaway-minuta-despacho/massa-de-testes/temp

# Nome da impressora (deixe vazio para apenas listar no inicio)
impressora.nome=NOME_DA_IMPRESSORA_AQUI