# Configuracoes da Automacao Impressao de Minuta GOL

# Pastas de entrada separadas por virgula
pastas.entrada=C:/projetos/seaway-minuta-despacho/massa-de-testes/entrada/FAT/CSV,C:/projetos/seaway-minuta-despacho/massa-de-testes/entrada/LOJA/MINUTA

# Pastas de destino e temporaria
pasta.processados=C:/projetos/seaway-minuta-despacho/massa-de-testes/processados
pasta.temp=C:/projetos/seaway-minuta-despacho/massa-de-testes/temp

# Nome da impressora (deixe vazio capturar a default do windows)
impressora.nome=NOME_DA_IMPRESSORA_AQUI
# Numero de vias a serem impressas
impressora.copias=2