# Configuraçãoes da Automação Impressão de Minuta GOL

# Pastas de entrada separadas por vírgula
pastas.entrada=\\\\fs-seaway\\lap\\FAT\\CSV,\\\\fs-seaway\\lap\\LOJA\\MINUTA

# Pastas de destino e temporária
pasta.processados=C:/automacao-minuta-gol/processados
pasta.temp=C:/automacao-minuta-gol/temp

# Nome da impressora (deixe vazio para apenas listar no inicio)
impressora.nome=SEC30CDA7CC11F5